apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: productpage-dev-route
spec:
  to:
    kind: Service
    name: productpage-dev
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  path: /WebApp
