apiVersion: v1
kind: Service
metadata:
  name: productpage-dev
spec:
  selector:
    app: productpage
    version: dev
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
