apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:234c8217dd1be712fae64cc1056fbc8422af19eaeaed7df4cc9a32a0a7dce36a
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:prod
