apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:aca81b96a459dd6f104a528fb4e7904adc5622203ca433f3378640f4b76a38c2
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:18a357f76d5ed097607327e713eeed2988b62d8b
