apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:efd7596e435ce84fb0bb014554b748f531a2181032e8deb7cc78fc7bd10521e9
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:1.1-SNAPSHOT
- digest: sha256:9c9980b2ddfc6c64c35d37bf5a1a1c9a8656fb055eefac37eb8176b97cc4c39e
  name: quay.io/rohanp/warproject:28161f54e7a3c46ec19de8f090c6baf589ae66ca
  newName: quay.io/rohanp/warproject:28161f54e7a3c46ec19de8f090c6baf589ae66ca
