apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:1b846ea6673d4ad5fae5531946bcd86dcea50a5bfc8bfc23061413819f559911
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:1.0
