apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:9b88303a64c6d23e23b02d8f53cdba972d3fb8ad9939a3ead23f19381551a852
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test
