apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:4a47cb502f1c3760cdb967dc6e2103c66bbc057ef596a0aa65c56853bdd0c756
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:prod
