apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:713f18b80046257bba735160afe099dee54233cc855283b4e910843b81d59696
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test
