apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:f37ae9b2597d77a1e755b001a7a71ea3b3989546d7e74a25e79037d785599626
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:18a357f76d5ed097607327e713eeed2988b62d8b
