apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:36914cc0f81a617a8ad720f1bbf74e69c04f9176e9bc4efcad7a556c7fc81823
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:prod
