apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:cd22252111b81f8004b3c389f3b3bd5ec01dfd0d7e01da3f2cbd7bb7ebc997b9
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:prod
