apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:efd7596e435ce84fb0bb014554b748f531a2181032e8deb7cc78fc7bd10521e9
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:1.1-SNAPSHOT
- digest: sha256:8e02afc188bd841e5fb4a0dfdbb69b8a49ccf3a4e04add28290a90891cd3d8e5
  name: quay.io/rohanp/warproject:28161f54e7a3c46ec19de8f090c6baf589ae66ca
  newName: quay.io/rohanp/warproject:28161f54e7a3c46ec19de8f090c6baf589ae66ca
