apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:3a907e4de94587ab31db1979429d77351205fed18e932872d65a3639cbe7fef7
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:18a357f76d5ed097607327e713eeed2988b62d8b
