apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:5bd3bc55db9cc06c96a07f98257951fc6a1d421a8632f113c3fc4a77d6287a97
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:1.1-SNAPSHOT
