apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:aed7e8b58b1cdb9cd6d80603d342e52855f9ac60624d77d1eac3212663e30a2a
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:18a357f76d5ed097607327e713eeed2988b62d8b
