apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:743f5f7409f02cac8c9a72923a3671077f208694fcb0e3813ab686658f7587d6
  name: quay.io/rohanp/warproject
  newName: quay.io/rohanp/warproject:test
